<?php require_once __DIR__ . '/admin_guard.php'; ?>
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="favicon/favicon.ico" sizes="any"><link rel="icon" type="image/png" sizes="32x32" href="favicon/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="favicon/favicon-16x16.png"><link rel="apple-touch-icon" sizes="180x180" href="favicon/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="192x192" href="favicon/android-chrome-192x192.png"><link rel="icon" type="image/png" sizes="512x512" href="favicon/android-chrome-512x512.png"><title>Admin — Baiku</title><link rel="stylesheet" href="css/style.css"></head>
<body>
<div class="announcement">Free shipping worldwide over $100 · Easy returns · Authentic gear only</div>
<header class="header"><div class="container nav">
<nav class="nav-links"><a href="shop.html">Shop</a><a href="shop.html?category=Helmets">Helmets</a><a href="shop.html?category=Jackets">Jackets</a><a href="shop.html?category=Pants">Pants</a><a href="shop.html?category=Boots">Boots</a><a href="index.html">Storefront</a></nav>
<a class="logo" href="index.html"><span class="logo-main">Baiku</span><span class="logo-sub">RIDING GEAR</span></a>
<div class="nav-actions"><button class="user-name admin-account-trigger" type="button" id="adminAccount" aria-haspopup="menu" aria-expanded="false"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="7" r="4"/><path d="M4 21c.7-4.1 3.3-6 8-6s7.3 1.9 8 6"/></svg> Baiku Admin</button><button class="icon-btn" id="adminLogout" title="Sign out" aria-label="Sign out">↪</button></div>
</div></header>
<main class="admin-shell"><div class="container admin-header"><div class="admin-brand-row"><div><div class="section-kicker">Baiku Admin</div><h1 class="admin-title">Dashboard</h1></div><button class="btn secondary" id="refreshAdmin">Refresh</button></div></div>
<div class="container admin-layout"><aside class="admin-side"><button class="active" data-admin-tab="overview">Overview</button><button data-admin-tab="products">Products</button><button data-admin-tab="orders">Orders</button><button data-admin-tab="customers">Customers</button></aside>
<section class="admin-main">
<div id="adminMessage" class="auth-message" aria-live="polite"></div>
<section class="admin-panel" data-panel="overview"><h2 class="admin-section-title">Overview</h2><div class="stat-grid admin-stat-grid"><div class="stat"><span>Active products</span><strong id="statProducts">—</strong></div><div class="stat"><span>Orders</span><strong id="statOrders">—</strong></div><div class="stat"><span>Customers</span><strong id="statCustomers">—</strong></div><div class="stat"><span>Revenue</span><strong id="statRevenue">—</strong></div></div><h3 class="admin-subtitle">Recent orders</h3><div class="table-wrap"><table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody id="recentOrders"><tr><td colspan="5">Loading…</td></tr></tbody></table></div></section>
<section class="admin-panel" data-panel="products" hidden><div class="admin-panel-head"><div><h2 class="admin-section-title">Products</h2><p class="admin-muted">Create, edit, feature, deactivate, and restore catalog products.</p></div><button class="btn" id="newProduct">Add product →</button></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Featured</th><th>Status</th><th>Actions</th></tr></thead><tbody id="productsTable"><tr><td colspan="7">Loading…</td></tr></tbody></table></div></section>
<section class="admin-panel" data-panel="orders" hidden><div class="admin-panel-head"><div><h2 class="admin-section-title">Orders</h2><p class="admin-muted">Review order details and update fulfillment status.</p></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody id="ordersTable"><tr><td colspan="7">Loading…</td></tr></tbody></table></div><div id="orderDetail" class="order-detail" hidden></div></section>
<section class="admin-panel" data-panel="customers" hidden><div class="admin-panel-head"><div><h2 class="admin-section-title">Customers</h2><p class="admin-muted">Registered customer accounts and their order totals.</p></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Customer</th><th>Email</th><th>Orders</th><th>Spent</th><th>Joined</th></tr></thead><tbody id="customersTable"><tr><td colspan="5">Loading…</td></tr></tbody></table></div></section>
</section></div></main>
<div class="admin-modal-backdrop" id="productModal"><div class="admin-modal"><div class="admin-panel-head"><div><div class="section-kicker">Catalog</div><h2 id="productModalTitle">Add product</h2></div><button class="icon-btn" id="closeProductModal" aria-label="Close">×</button></div><form id="productForm" class="form-grid admin-form"><input type="hidden" id="productId"><div class="field"><label>Name</label><input id="productName" required maxlength="150"></div><div class="field"><label>Description</label><textarea id="productDescription" rows="4" required></textarea></div><div class="admin-form-grid"><div class="field"><label>Price (Rs.)</label><input id="productPrice" type="number" min="0" step="0.01" required></div><div class="field"><label>Stock</label><input id="productStock" type="number" min="0" step="1" required></div><div class="field"><label>Category</label><select id="productCategory" required><option>Helmets</option><option>Jackets</option><option>Pants</option><option>Boots</option></select></div></div><div class="field"><label>Image path or URL</label><input id="productImage" placeholder="images/helmet-1.jpg" required maxlength="500"></div><div class="admin-checks"><label><input type="checkbox" id="productFeatured"> Featured product</label><label><input type="checkbox" id="productActive" checked> Active on storefront</label></div><div class="admin-modal-actions"><button type="button" class="btn secondary" id="cancelProduct">Cancel</button><button class="btn" id="saveProduct">Save product →</button></div></form></div></div>
<script src="js/admin.js"></script>
</body></html>
